source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CurrencyRequest_Example', :exclusive => true do
  pod "CurrencyRequest", :path => "../"
end

target 'CurrencyRequest_Tests', :exclusive => true do
  pod "CurrencyRequest", :path => "../"
end
